context:
  name: chexus
  version: "26.9.0"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/chexus-${{ version }}.tar.gz
  sha256: 18f28d4b8e1a6652de49cc3a22e8e01f866bf327c80787b70d5970c302c1b802

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - chexus = chexus.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=68
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=${{ python_min }}
    - h5py

tests:
  - python:
      imports:
        - chexus
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - chexus --help

about:
  summary: Validate and check NeXus files
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/scipp/chexus
  homepage: https://scipp.github.io/chexus/

extra:
  recipe-maintainers:
    - MridulS
